### PR TITLE
Adding compatibility for python 3.11

### PR DESCRIPTION
**Pull request by Fried-Squid**
Updates to make the package compatible with python 3.11

> Added single-character quotechar as a default and in all config.py TABLE_CSV_PARAMS as empty quotechars are no longer supported
> Added escapechar into datafile.DataFile which defaults to None as an empty escapechar is no longer supported
> Updated test for datafile.py to ensure it doesn't try and test with a "" quotechar as this will always fail
> Updated relevant docstrings

### CODE REVIEW

**Comment by Fried-Squid** [comment]
Note that the Pandas library changed the line_terminator kwarg of DataFrame.to_csv to lineterminator:

> Changed in version 1.5.0: Previously was line_terminator, changed for consistency with read_csv and the standard library ‘csv’ module.

(see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)

So this will fail tests for Pandas < 1.5.0, and Pandas 1.5.0 supports python >= 3.8.

I'm unsure how to approach this issue, is it possible to do different releases for versions of python < 3.8 ?

**Comment by Fried-Squid** [comment]
Updated requirements.txt, see above

**Comment by Fried-Squid** [comment]
Builds fine when removing 3.7 from the CI workflow, should this be removed from the CI versions and replaced with 3.11?
https://github.com/Fried-Squid/tatoebatools_311_fix/actions/runs/5289968415

In support of this, EOL for python 3.7 is in 11 days anyway, so it seems like a good time to remove 3.7 from the CI script and only build the package for python >= 3.8 and by extension Pandas >= 1.5.0

**Comment by LBeaudoux** [comment]
@Fried-Squid thank you so much for taking the time to find a solution to this bug. Your PR looks good. I'll take a closer look at it this weekend.

**Comment by Fried-Squid** [comment]
@LBeaudoux More than happy! Been using this library for longer than I can remember, its the least I can do. Let me know if there's anything else I can help with to fix this issue.

**Pull request merged**
