### PR TITLE
Add tox and GitHub Actions CI for Python 3.6–3.9

### PR DESCRIPTION
**Pull request by eumiro**
Since there's still no GHA in the `master` branch, the result of this CI run won't be visible immediately, but is expected to be shown at https://github.com/eumiro/tatoebatools/actions

After merge a badge will show in the project's README as well as near every PR against `master`.

### CODE REVIEW

**Comment by LBeaudoux** [comment]
I finally decided to implement CI on this project! @eumiro, thanks for this pull request; the combination of tox and Github Actions is appealing.

You chose to use the [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions) plugin as advised by Hynek Schlawack in this [blog post](https://hynek.me/articles/python-github-actions/). The official Github documentation highlights [another solution](https://docs.github.com/en/actions/guides/building-and-testing-python#running-tests-with-tox) without plugin that is easier to understand. Maybe we should favor this simpler option to start with?

I also noticed that you run the tests only on Linux and not on Windows and macOS. Is it on purpose?

**Comment by eumiro** [comment]
I am used to the `tox-gh-actions` plugin, but it can certainly be done also without it. If you prefer the pluginless version, I can happily adapt my PR.

Also the tested OS is a matter of personal experience. I believe the suggested GHA config should work for `macos-latest` as well, but not directly for `windows-latest` because some stuff should be written differently.

**Comment by LBeaudoux** [comment]
Since I am not a tox user, I would like to run the tests simply with pytest for now. 

Thanks for making me discover the existence of GitHub Actions. It's very handy, I use it now for the CI and the publishing of my [iso639-lang](https://github.com/LBeaudoux/iso639) library.

**Comment by eumiro** [comment]
Happy to hear that. `tox` will help you to run the tests locally on all available Python versions, but on GHA you can run it directly with pytest.

**Pull request merged**
